"""
================================================================================
SUPABASE CLIENT CONFIGURATION & SQL SCHEMA FOR OCCUPIED APP
================================================================================

Copy and run the following SQL block in your Supabase Dashboard:
(Go to Supabase Dashboard -> Project -> SQL Editor -> New query -> Run)

----------------------------------- SQL SCHEMA ---------------------------------

-- 1. Create Activities Table
CREATE TABLE IF NOT EXISTS public.activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    duration_minutes INTEGER NOT NULL,
    logged_at DATE NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Create Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    color TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, name)
);

-- 3. Create Goals Table
CREATE TABLE IF NOT EXISTS public.goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    target_hours NUMERIC NOT NULL DEFAULT 0,
    current_progress NUMERIC NOT NULL DEFAULT 0,
    period TEXT NOT NULL DEFAULT 'weekly',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, name, period)
);

-- 4. Enable Row Level Security (RLS) on all tables
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.goals ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS Policies for Activities (Users can only view, insert, update, delete their own data)
CREATE POLICY "Users can manage their own activities"
    ON public.activities
    FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- 6. Create RLS Policies for Categories
CREATE POLICY "Users can manage their own categories"
    ON public.categories
    FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- 7. Create RLS Policies for Goals
CREATE POLICY "Users can manage their own goals"
    ON public.goals
    FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

--------------------------------------------------------------------------------
"""

import os
from supabase import create_client, Client

# Replace with your actual Supabase project URL and anon public key from Project Settings > API before running.
SUPABASE_URL = "https://qjfdcvxvrgpvpjsyaeaj.supabase.co"

SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqZmRjdnh2cmdwdnBqc3lhZWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc1NTkyNjAsImV4cCI6MjEwMzEzNTI2MH0.hRlnVTOzVBHnhxkhrsg1sG6od428QXD-rFZdTjOgnTY"

_supabase_client = None


def is_configured() -> bool:
    """Check if real Supabase credentials have been configured."""
    return (
        bool(SUPABASE_URL)
        and SUPABASE_URL != "YOUR_SUPABASE_URL_HERE"
        and bool(SUPABASE_KEY)
        and SUPABASE_KEY != "YOUR_SUPABASE_ANON_KEY_HERE"
    )


def get_supabase() -> Client:
    """Initialize and return the Supabase client singleton."""
    global _supabase_client
    if _supabase_client is not None:
        return _supabase_client

    if not is_configured():
        raise ValueError(
            "Supabase credentials not configured.\n"
            "Please open 'supabase_client.py' and set your real SUPABASE_URL and SUPABASE_KEY "
            "from your Supabase Dashboard (Project Settings > API)."
        )

    _supabase_client = create_client(SUPABASE_URL, SUPABASE_KEY)
    return _supabase_client
